# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[workspace]
members = ["api", "application", "domain", "infrastructure", "shared"]


[workspace.dependencies]

axum = "0.6.18"
serde = { version = "1" }
serde_json = "1"
